# Generated by Django 5.1.7 on 2026-02-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="blog/")),
                ("content", models.TextField()),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in the home page swiper"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("SUV", "SUV"),
                            ("Sedan", "Sedan"),
                            ("Hatchback", "Hatchback"),
                        ],
                        default="SUV",
                        max_length=50,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Electric", "Electric"),
                        ],
                        default="Petrol",
                        max_length=50,
                    ),
                ),
                ("seats", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                        default="Automatic",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated list, e.g., A/C, 4WD",
                        null=True,
                    ),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Finally, Professional Car & Scooter rent possible with Vema Cars",
                        max_length=255,
                    ),
                ),
                (
                    "ticks",
                    models.TextField(
                        help_text="Enter items separated by a comma (e.g. Simple booking, Quick support)"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                ("cta_text", models.CharField(default="Go to Booking", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Used for the Car Card display"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.car",
                    ),
                ),
            ],
        ),
    ]
