# Generated by Django 5.1.7 on 2026-02-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_booking_bookingcustomerinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="dropoff_location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="extras",
            field=models.ManyToManyField(blank=True, to="api.extra"),
        ),
    ]
