# Generated by Django 6.0.1 on 2026-01-08 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vemacars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="amenities",
            field=models.TextField(
                blank=True, help_text="Comma separated list, e.g., A/C, 4WD", null=True
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                ],
                default="SUV",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="location",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="car",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="carimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Used for the Car Card display"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Electric", "Electric"),
                ],
                default="Petrol",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                default="Automatic",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(upload_to="cars/"),
        ),
    ]
