# Generated by Django 6.0.1 on 2026-01-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vemacars", "0002_car_amenities_car_car_type_car_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="location", field=models.CharField(max_length=255),
        ),
    ]
