# Generated by Django 6.0.1 on 2026-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vemacars", "0003_alter_car_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Finally, Professional Car & Scooter rent possible with Vema Cars",
                        max_length=255,
                    ),
                ),
                (
                    "ticks",
                    models.TextField(
                        help_text="Enter items separated by a comma (e.g. Simple booking, Quick support)"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                ("cta_text", models.CharField(default="Go to Booking", max_length=50)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
    ]
