# Generated by Django 5.1.7 on 2026-02-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vemacars", "0005_blogpost_herosection_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="BlogPost",),
        migrations.RemoveField(model_name="carimage", name="car",),
        migrations.DeleteModel(name="HeroSection",),
        migrations.DeleteModel(name="Car",),
        migrations.DeleteModel(name="CarImage",),
    ]
